# Generated by Django 3.1.7 on 2021-04-08 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('revistas', '0001_initial'),
        ('posts', '0004_auto_20210408_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='revistaAssociada',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='revistas.revista'),
        ),
    ]
