# Generated by Django 3.1.7 on 2021-04-28 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20210408_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='usuario',
        ),
    ]
