# Generated by Django 3.1.7 on 2021-03-25 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20210322_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='revista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.revista'),
        ),
    ]
